	'sign_onetime'=>'签到一次获得金币',
	'sign_alltime_3'=>'连续签到3天获得金币',
	'sign_alltime_7'=>'连续签到7天获得金币',
    'sign_alltime_15'=>'连续签到15天获得金币',
    'sign_alltime_30'=>'连续签到30天获得金币',
    'confirm_success'=>'修改成功',
    'user_sign'=>'每日签到',
    'user_sign2'=>'已签到',
