	'partner'=>'合作身份者id，以2088开头的16位纯数字',
	'seller_email'=>'收款支付宝账号',
	'app_key'=>'安全检验码，以数字和字母组成的32位字符',
    'confirm_success'=>'修改成功',
    'user_recharge'=>'充值',
    'enable'=>'是否开启',
    'appid'=>'微信公众号身份的唯一标识APPID',
    'appsecert'=>'JSAPI接口中获取appsecert',
    'seller_id'=>'商户号',
    'app_key'=>'商户支付密钥Key',
    'recharge_money'=>'充值金额',
    'recharge_time'=>'充值时间',
    'recharge_order_sn'=>'网站订单号',
    'trade_no'=>'交易订单号',
        'please_check_delete_recharge'=>'请勾选您要删除的记录',
    'recharge_delete_confirm'=>'确定要删除记录吗',    

    
